general.import = ["~/.config/alacritty/themes/catppuccin_macchiato.toml"]
general.live_config_reload = true

[env]
TERM = "alacritty"
EDITOR = "hx"

[window]
opacity = 0.9

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true
