import = ["~/.config/alacritty/themes/kaganawa_wave.toml"]
live_config_reload = true

[env]
TERM = "alacritty"
EDITOR = "helix"
# WINIT_X11_SCALE_FACTOR = "1.66"

[window]
# decoration = "None"
opacity = 0.9

[font]
# normal = {family = "CodeNewRomanNerdFontMono", style="Regular"}
# bold = {family = "CodeNewRomanNerdFontMono", style="Bold"}
# italic = {family = "CodeNewRomanNerdFontMono", style="Italic"}
size = 11

[selection]
save_to_clipboard = true
